### ISSUE TITLE
calculate variance data

### ISSUE THREAD

**Issue by ebeshero** [PghFrankenstein/Pittsburgh_Frankenstein#37]
Think about how best to do this, with destination = reading interface and highlighting of variants with "hot" to "cool" colors from most to least significant.

Levenshtein distance (calculated by character) seems like a good way to group variants in ranges...HOWEVER:
What if we have a variant in which one letter difference makes two completely different semantic words? (e.g. **code** vs. **cove**)? 

To deal: test for equality of word tokens when these are not in the normalization list.  

Work with assessment of word tokens AND the Levenshtein distances to estimate the range of significance of a variant.

**Comment by ebeshero** [comment]
I'm returning to this issue right now, as we're preparing finalized "spine" files holding small portions of variant text. The question is, what is the best way to calculate Levenshtein distances for our project? I think we should experiment with a weighted-Levenshtein approach that allows us to adjust edit-distance scores for distinct kinds of edits, but we need to think about how we want to do this--what makes sense for the kinds of edits we are seeing in _Frankenstein_. 

Basically the weighted Levenshtein approach lets you score edit distances differently, if you want, if they detect changes based on:
* insertion (add a character)
* deletion (delete a character)
* substitution (replace one character for another)
* transposition (rearrange characters)

So, we've seen examples of all of these things, especially in looking at comparisons of the manuscript notebooks to the 1818 edition. The later editions make changes that are more like bulk additions and deletions. But the movement from manuscript to print seems to involve a lot of small changes to spelling, additions or deletions of punctuation, etc. And the question is, do we want to make some decisions about scoring some of these changes as more significant than others in evaluating intensity of variation?

Reality check: We have two use-cases for Levenshtein calculation:
1) to control the intensity of hue in highlighting hotspots
2) to help us build infographics surveying which portions of the edition contain the most significant "molten" alterations.
In these terms, it may not matter very much whether/how we weight a Levenshtein distance calculation. But I'd appreciate the wisdom of the group and those watching our repo on this--some of you have been working with edit distances longer than I have!

Here's documentation on a Python implementation of weighted-levenshtein that I'm likely to follow: <https://weighted-levenshtein.readthedocs.io/en/master/>  

@raffazizzi @scottbot @mdlincoln @djbpitt

**Comment by ebeshero** [comment]
My idea right now is that that transpositions should be scored less than additions and deletions. We see so much simple reversal of letters in the MS that it doesn't seem as semantically significant. I'm not so sure about substitutions--maybe we should keep adds, deletes, and substitutions at the same level, and score transpositions lower?

**Comment by raffazizzi** [comment]
I think blatant corrections (by deletion, addition, transposition, or a combination of these) in the ms (eg. man~~o~~<sup>u</sup>script) should not be scored, or scored lowest since they may still appear as a "variant" reading (even though, truth be told, they're not).

On the other hand, changes in words that got discarded could be scored higher, even as much as a regular variant. For example "The ~~swift~~ <sup>quick</sup> brown fox" is interesting even if all texts agree on "quick" because it shows the genesis of the work (I bet there is terminology regarding these phenomena in the critique génétique literature, but how far do we want to go in terms of rigor?).

It's tempting to use Levenshtein values to get an idea of variance at character level, but is that useful? I wonder if it might be best to have a handful of categories of variance and use the Levenshtein analysis to assign variants to these categories. Each category could correspond to a range of Levenshtein values and if we need to make manual corrections of judgement calls, we just pick the median value in that range.

**Comment by ebeshero** [comment]
Note presence of `<del>` tags as a factor...

**Comment by ebeshero** [comment]
Quick update on this issue: We decided at our meeting with @scottbot, @Rikkm, and @raffazizzi yesterday that maximum or average Levenshtein calculations are more appropriate for our use. My preference is the maximum value since it will likely help to make the strongest variations stand out the most. 

I have now output those values and applied them to our standoff_Spine directory for use in the Variorum interface, here: https://github.com/PghFrankenstein/fv-postCollation/tree/master/standoff_Spine   (This is also posted in the fv-data repo, which just holds our finalized files for the Variorum). 

 The more complete variant data on each rdgGrp's pairwise comparison with other rdgGrps in its app location is available in tidied up form here: https://github.com/PghFrankenstein/fv-postCollation/blob/master/edit-distance/FV_LevDists-weighted.xml

**Comment by ebeshero** [comment]
In the standoff_Spine directory, the Levenshtein maximum value for each `<app>` element is posted in its `@n` attribute.
