### ISSUE TITLE
Wireframe / Prototype Prep

### ISSUE THREAD

**Issue by ebeshero** [PghFrankenstein/Pittsburgh_Frankenstein#50]
@Rikkm would like me to pull in Levenshtein distances on each app so we can style the hotspots by hue indicating a rough measure of variance.

**Comment by ebeshero** [comment]
@Rikkm Simple classList toggle tutorial I wrote: http://dh.obdurodon.org/javascript/classListToggle.xhtml

**Comment by ebeshero** [comment]
@Rikkm Here's my Mitford play prototype, too:
http://digitalmitford.org/ChasIpub.html

**Comment by djbpitt** [comment]
@ebeshero I like the Levenshtein idea! You probably already have a strategy for dealing with the following, but just in case:

1. Levenshtein values are sensitive to the length of the strings being compared, since longer strings can be more distant from each other than shorter ones. This may mean normalizing the values according to the length of the longest string.
1. Levenstein distance compares just two strings. I'm not sure what this might mean for finding hotspots in a collation of more than two witnesses.

**Comment by ebeshero** [comment]
@djbpitt Yep—I’ll need to make all the possible comparisons of 5 things taken 2 at a time, and then choose the max of the output comparison numbers...

**Comment by ebeshero** [comment]
@djbpitt I am thinking about the longest-string problem. Strings will be lengthened when they contain markup, so I should find a strategy to read around those. Since I need to do this in Python anyway, it’ll probably involve the same normalization as the collation itself!
